# Generated by Django 3.0.8 on 2020-11-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
